version: '3'
services:
  opencart:
    build: tools
    user: 1000:1000
    ports:
      - "80:80"
    volumes:
      - ./upload:/var/www/html
    depends_on:
      - mysql
    env_file:
      - .env
    command: >
      bash -c "chown -R 1000:1000 /var/www/html &&
               chmod -R 755 /var/www/html &&
               if [ ! -f /var/www/html/install.lock ]; then
                 wait-for-it ${OPENCART_DB_HOSTNAME}:${OPENCART_DB_PORT} -t 60 &&
                 cp /var/www/html/config-dist.php /var/www/html/config.php &&
                 cp /var/www/html/admin/config-dist.php /var/www/html/admin/config.php &&
                 php /var/www/html/install/cli_install.php install --username ${OPENCART_ADMIN_USERNAME} --password ${OPENCART_ADMIN_PASSWORD} --email ${OPENCART_ADMIN_EMAIL} --http_server ${OPENCART_HTTP_SERVER} --db_driver ${OPENCART_DB_DRIVER} --db_hostname ${OPENCART_DB_HOSTNAME} --db_username ${OPENCART_DB_USERNAME} --db_password ${OPENCART_DB_PASSWORD} --db_database ${OPENCART_DB_DATABASE} --db_port ${OPENCART_DB_PORT} --db_prefix ${OPENCART_DB_PREFIX} &&
                 touch /var/www/html/install.lock;
               fi &&
               apache2-foreground"

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    env_file:
      - .env

  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    depends_on:
      - mysql
    ports:
      - "8080:8080"

  redis:
    image: redis:latest

  memcached:
    image: memcached:latest

  postgres:
    image: postgres:latest
    env_file:
      - .env